USE adlister_db;
DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE ads (
    id INT UNSIGNED NOT NULL AUTO-INCREMENT,
    user_id INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL
    PRIMARY KEY (id)
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO-INCREMENT,
    username VARCHAR(36) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(36) NOT NULL
    PRIMARY KEY (id)
);